Feat: Add 'Lock Initiative' button
fvtt-fria-ligan/yearzero-combat-fvtt pull request #32
Opened 2023-08-20 07:16 UTC by aMediocreDad

After some consideration, I believe the cleanest way to allow users to use functionality like the 'Veteran'-ability in Dragonbane is to implement it in Year Zero Combat itself (it requires changing how some internal methods execute and we cannot expose that in a configurable manner).

The buttons for locking initiative will now appear by default when 'Reset the Initiative Each Round' is selected.

The resetInitiativeDeck has seen some change in it's functionality as a result. Instead of using 'recall' we now use 'pass' and supply a filtered list of cards this allows us to keep the initiative cards we want to keep between draws in the discard pile.

## Summary

## Checklist

### PR Type

- [ ] This PR is a code change that implements a feature request.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR fixes an issue.
- [ ] This PR is not a code change (e.g. documentation, README, ...)

### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes.

2023-08-20 07:59 UTC, Stefouch requested changes
Tested and stressed the new settings, and there are lots of issues with this PR:
1. On next round, initiative is reset as expected, but not automatically redrawn.
2. Going back on previous round, previous initiative scores are lost (no memory).
3. Locked initiative does not work for combatant groups (leader is locked, but not other members of the group).

2023-08-20 07:59 UTC, Stefouch commented on src/utils/utils.js
>   * @param {boolean} [chatNotification=false] Whether to send a chat notification.
Improving the documentation:
```suggestion
 * @param {boolean} [chatNotification=false] Whether to send a chat notification.
 * @param {number[]} [toExclude=[]] Array of card values to exclude from the reset.
```

2023-08-20 18:49 UTC, aMediocreDad commented on src/module/settings.js
> +
I realize I have completely misunderstood the intention with the "Automatically Draw Initiative" setting. Only when working with the drawing rules did it dawn on me. 

Seeing that the wording is bad I elected to create a new setting that conveys the intention of the one above and replaces it. A migration could be done, but I think I am not the only one who has misunderstood the intention of said setting (and the effect of not migrating is fairly harmless).

2023-08-21 09:10 UTC, Stefouch requested changes
There is a small issue with the lock initiative button: locking initiative before combat start will throw an error when started.
- Would be best to hide the lock button before round 1. ( `game.combat?.round > 0` )
- Also hide the lock initiative button for follower combattants since their init depends on the group leader.

2023-08-21 09:10 UTC, Stefouch commented on src/module/settings.js
> +
OK, I'm with you on this. I tested the settings and they work as expected:
| initAutoDraw | autoSelectBestCard | Effect |
| --- | --- | --- |
| - | - | Nothing automatically drawn as expected |
| ✔️ | - | OK |
| - | ✔️ |  OK |
| ✔️ | ✔️ | OK, as expected |

2023-08-21 09:10 UTC, Stefouch commented on src/combat/combat.js
> +
Prettier has been weird here. Suggested change:
```suggestion
        if (game.settings.get(MODULE_ID, SETTINGS_KEYS.AUTO_SELECT_BEST_CARD)) {
          card = cards[0];
        }
        else {
          card = await this.chooseCard(cards, combatant);
        }
      }
      else {
        card = cards[0];
      }

```

2023-08-21 09:10 UTC, Stefouch commented on src/module/config.js
> +    ],
Clicking this button before combat is started will throw an error.
Is it possible to hide the button before combat is started?

Maybe add a condition in YearZeroCombatTracker.#getButtonConfig() ?

2023-08-21 16:53 UTC, aMediocreDad commented on src/module/config.js
> +    ],
This one is worse. We cannot (should not) serialize conditionals to be evaluated runtime. We could perhaps provide this API through programmatic setup however.

2023-08-21 17:33 UTC, Stefouch approved these changes
Expect for the single extra suggestion, I think everything is ready for merge.

2023-08-21 17:33 UTC, Stefouch commented on src/module/settings.js
>      default: false,
Suggesting `requiresReload = true` so the combat-tracker is refreshed and the lock icon appear/disappear properly.
```suggestion
    default: false,
    requiresReload: true,
```

2023-08-21 18:31 UTC, Stefouch approved these changes

2023-08-21 20:58 UTC, merged